// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5VvM9sGeeXiGjl8Cnpz3ykylaZYx2n8U',
    appId: '1:807672020521:web:a0d18b84f2d6461f46e638',
    messagingSenderId: '807672020521',
    projectId: 'healthmate-lk',
    authDomain: 'healthmate-lk.firebaseapp.com',
    storageBucket: 'healthmate-lk.appspot.com',
    measurementId: 'G-Y0FK3S25B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHTnMxX1BL8fOQf9MGnUqPs-_Lu_b2Fdo',
    appId: '1:807672020521:android:97703a503491462b46e638',
    messagingSenderId: '807672020521',
    projectId: 'healthmate-lk',
    storageBucket: 'healthmate-lk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2j6cJbdMuh4NNr8sirRT3qCqF3NKCEOY',
    appId: '1:807672020521:ios:a4f22bdbf36c94bd46e638',
    messagingSenderId: '807672020521',
    projectId: 'healthmate-lk',
    storageBucket: 'healthmate-lk.appspot.com',
    iosBundleId: 'com.example.sMedi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2j6cJbdMuh4NNr8sirRT3qCqF3NKCEOY',
    appId: '1:807672020521:ios:f2338f51f25ec46146e638',
    messagingSenderId: '807672020521',
    projectId: 'healthmate-lk',
    storageBucket: 'healthmate-lk.appspot.com',
    iosBundleId: 'com.example.sMedi.RunnerTests',
  );
}
